### ISSUE TITLE
segfault in 64-bit compile

### ISSUE THREAD

**Issue by jamesbond3142** [JoesCat/xinvaders3d#1]
As the title says. Here is the fix.
```
diff -ur xinvaders3d-ccc2f894dfbb5f04f0a8a9d92d5bc675dc365746/externs.h xinvaders3d-new/externs.h
--- xinvaders3d-ccc2f894dfbb5f04f0a8a9d92d5bc675dc365746/externs.h	2023-06-23 19:15:29.000000000 +1000
+++ xinvaders3d-new/externs.h	2023-07-11 01:24:56.232492423 +1000
@@ -62,8 +62,8 @@
    long pbonus;    /* player bonus counter */
    int  plives;    /* player's current # of lives */
    int  pblinking; /* player invunerable */
-   int  hi_score_c[20];
-   int  pscore_c[20];
+   int *hi_score_c[20];
+   int *pscore_c[20];
 };
 
 /* game.c */
```

While we're at it, it's nice to make the implicit conversion to explicit (for systems that have lrint):

```
diff -ur xinvaders3d-ccc2f894dfbb5f04f0a8a9d92d5bc675dc365746/game.c xinvaders3d-new/game.c
--- xinvaders3d-ccc2f894dfbb5f04f0a8a9d92d5bc675dc365746/game.c	2023-06-23 19:15:29.000000000 +1000
+++ xinvaders3d-new/game.c	2023-07-11 01:27:17.590496351 +1000
@@ -625,8 +625,8 @@
 
 void Object_update_zone ( OBJECT *obj )
 {
-   obj->zone    = (int) floor ( (double)obj->pos[ZPOS]/-ZONE_WIDTH  );
-   obj->zheight = (int) floor ( (double)obj->pos[YPOS]/ZONE_HEIGHT );
+   obj->zone    = lrint ( floor ( (double)obj->pos[ZPOS]/-ZONE_WIDTH  ) );
+   obj->zheight = lrint ( floor ( (double)obj->pos[YPOS]/ZONE_HEIGHT ) );
 }
 
 /*================================================================*/

```

**Comment by JoesCat** [comment]
Thanks @jamesbond3142 - nice!
I was expecting *hi_score_c[20] & *pscore_c[20] to cause problems, but I must be thinking of *hi_score_c[] & *pscore_c[] which would require both malloc() and free().
...Except for X11, seems the game is built with global variables that don't use malloc() or free()

Good hint about lrint(),
Checking the linux lrint man page, seems we're okay here since linux already meets POSIX standards:
_ISOC99_SOURCE || _POSIX_C_SOURCE >= 200112L

I'll put together a patch today.
Do you want credit as jamesbond3142 ?

**Comment by jamesbond3142** [comment]
That would be nice :smile:  
Thank you for continuing to maintain xinvaders3d in the first place :+1:

**Comment by JoesCat** [comment]
Added your fixes.
Closing this issue as resolved.
Just one further patch to add, and I think we'll call that ver 1.6 - soon.
